config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  devise_for :users,controllers: { omniauth_callbacks: 'omniauth' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/cities', to: 'home#getcities'
  resources :accountdetails, path: 'account_details' do
    collection do
      get 'accountdetails/:user_id', to: 'accountdetails#index', as: :details
    end
  end
  
  get '/companies', to: 'home#getdepartments'
  namespace :admin do
    resources :users
  end

  namespace :employee do
    resources :users, only: %i[show]
  end

  namespace :superadmin do
    resources :users do
      collection { post :import }
    end
    resources :companies do
      resources :departments
    end
  end

  namespace 'api' do
    namespace 'v1' do
      devise_for :users, defaults: { format: :json },
                         controllers: { sessions: 'api/v1/api_sessions', registrations: 'api/v1/api_registrations' }
      resources :users, except: %i[new edit]
    end
  end
  resources :memberships, only: %i[new]
  post :create_order, to: 'memberships#create_order'
  post :capture_order, to: 'memberships#capture_order'

  get '/users', to: 'posts#users'
  post 'users/:id/posts', to: 'posts#save_post'
  post 'users/:id/post', to: 'posts#create_post'
end

app/models/accountdetail.rb
class Accountdetail < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/controllers/accountdetails_controller.rb
class AccountdetailsController < ApplicationController
  load_and_authorize_resource param_method: :account_detail_params
  before_action :set_account_detail, only: %i[show edit update destroy]

  def index
    @accountdetails = Accountdetail.where(user_id: params[:user_id])
  end

  def show; end

  def new
    @accountdetail = Accountdetail.new
    @accountdetail.user_id = params[:user_id]
  end

  def create
    accountdetail = CreateAccountDetail.new(Accountdetail.new(account_detail_params), current_user).call
    if accountdetail
      redirect_to accountdetails_path
    else
      render :new
    end
    # @accountdetail = Accountdetail.new(account_detail_params)
    # if current_user.has_role? :superadmin or current_user.has_role? :admin
    #     @accountdetail.account_type = "company"
    # else
    #     @accountdetail.account_type = "personal"
    # end
    # if @accountdetail.save
    #     redirect_to accountdetails_path
    # else
    #     render :new
    # end
  end

  def edit; end

  def update
    if @accountdetail.update(account_detail_params)
      redirect_to accountdetail_path
    else
      render :edit
    end
  end

  def destroy
    @accountdetail.destroy
    redirect_to accountdetails_path
  end

  private

  def account_detail_params
    params.require(:accountdetail).permit(:user_id, :branch_name, :account_number, :account_name, :account_type,
                                          :image)
  end

  def set_account_detail
    @accountdetail = Accountdetail.find(params[:id])
  end
end

app/views/accountdetails/edit.html.erb
<div class="container">
    <h2>Update Account details</h2>
    <%= render "layouts/form", url: accountdetail_path %>
</div>

app/views/accountdetails/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<%= flash_messages %>
<h1 class="text-center">Account Details</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Account Name</th>
      <th scope="col">Account Number</th>
      <th scope="col">Branch name</th>
      <th scope="col" colspan=3>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @accountdetails.each do |a| %>
      <tr>
        <td><%= a.id %></td>
        <td><%= a.account_name %></td>
        <td><%= a.account_number %></td>
        <td><%= a.branch_name %></td>
        <td><%= link_to 'Show', accountdetail_path(a) %></td>
        <td><%= link_to 'Edit', edit_accountdetail_path(a) %></td>
        <% if can? :destroy, a %>
        <td><%= link_to 'Destroy', accountdetail_path(a),method: :delete, data: { confirm: 'Are you sure?'} %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back to users', superadmin_users_path %>
</div>

app/views/accountdetails/new.html.erb
<div class="container">
<% if @accountdetail.errors.any? %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">Something went wrong!</h4>
    <ul>
    <% @accountdetail.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
    <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>
<% end %>
<h2>Add Account details</h2>
<%= render "layouts/form", url: accountdetails_path %>
</div>

app/views/accountdetails/show.html.erb
<div class="container">
    <h1>show page</h1>
    <p><b>Branch Name:</b><%= @accountdetail.branch_name %></p>
    <p><b>Account Number:</b><%= @accountdetail.account_number %></p>
    <p><b>Account Name:</b><%= @accountdetail.account_name %></p>
    <p><b>Image:</b></p><%= image_tag @accountdetail.image %>
    <div>
        <%= link_to 'Back to users', superadmin_users_path %>
    </div>
</div>