config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  devise_for :users,controllers: { omniauth_callbacks: 'omniauth' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/cities', to: 'home#getcities'
  resources :accountdetails, path: 'account_details' do
    collection do
      get 'accountdetails/:user_id', to: 'accountdetails#index', as: :details
    end
  end
  
  get '/companies', to: 'home#getdepartments'
  namespace :admin do
    resources :users
  end

  namespace :employee do
    resources :users, only: %i[show]
  end

  namespace :superadmin do
    resources :users do
      collection { post :import }
    end
    resources :companies do
      resources :departments
    end
  end

  namespace 'api' do
    namespace 'v1' do
      devise_for :users, defaults: { format: :json },
                         controllers: { sessions: 'api/v1/api_sessions', registrations: 'api/v1/api_registrations' }
      resources :users, except: %i[new edit]
    end
  end
  resources :memberships, only: %i[new]
  post :create_order, to: 'memberships#create_order'
  post :capture_order, to: 'memberships#capture_order'

  get '/users', to: 'posts#users'
  post 'users/:id/posts', to: 'posts#save_post'
  post 'users/:id/post', to: 'posts#create_post'
end

app/models/user.rb
# frozen_string_literal: true

# This model is for users.
class User < ApplicationRecord
  rolify
  include Discard::Model
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders] 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,:validatable, :omniauthable, omniauth_providers: [:google_oauth2, :facebook]
  before_create :assign_default_role
  belongs_to :city, optional: true
  belongs_to :state, optional: true
  belongs_to :company, optional: true
  belongs_to :department, optional: true
  has_many :accountdetails, inverse_of: :user
  has_many :posts, dependent: :destroy
  accepts_nested_attributes_for :accountdetails, allow_destroy: true
  validates :name, :phone, :gender, presence: true
  validates :email, presence: true, format: {with: URI::MailTo::EMAIL_REGEXP }
  scope :employee_and_admin_users, -> { where(roles: { name: %w[employee admin] }) }
  scope :employee_users, -> { where(roles: { name: 'employee' }) }
  scope :add_extra, -> { left_joins(:roles,:state,:city,:company).select("users.*, states.name as state_name, cities.name as city_name, companies.name as company_name") }

  def generate_jwt
    JWT.encode({ id: id, exp: 24.hours.from_now.to_i }, Rails.application.secrets.secret_key_base)
  end

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_initialize do | user |
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = provider_data.info.name
      user.save!
    end
  end
  
  def slug_candidates
    [
      :name,
      [:name, :gender]
    ]
  end

  def should_generate_new_friendly_id?
    name_changed?
  end

  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end

  def assign_default_role
    add_role(:employee)
  end

  def admin?
    has_role?(:admin)
  end

  def employee?
    has_role?(:employee)
  end

  def superadmin?
    has_role?(:superadmin)
  end

  def self.search(search)
    User.add_extra.employee_and_admin_users.where("users.name LIKE ?", "%#{search}%" )
  end

  def self.to_csv(users)
    attributes = %w{id name email phone gender company state city }
    CSV.generate do |csv|
      csv << attributes
      users.each do |result|
        csv << [result.id, result.name, result.email, result.phone, result.gender, result.company_name, result.state_name, result.city_name]
      end
    end
  end

  def self.import(file)
    result = []
    valid_result = []
    i = 1
    CSV.foreach(file.path, headers: true) do |row|
      user = User.new row.to_h
      if user.valid?
        valid_result << user
        i += 1
      else
        result << user.errors.full_messages
        result << i
        return result
      end
    end
    valid_result.each do |elem|
      elem.save
    end
    result << "success"
    return result
  end 
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  # This controller is for AdminUser
  class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_admin_user, only: %i[show edit update destroy]
    before_action :restrict_user
    load_and_authorize_resource param_method: :admin_params
    def index
      @users = User.left_joins(:roles,:state,:city,:company).select("users.*, states.name as state_name, cities.name as city_name, companies.name as company_name").employee_users.kept
    end

    def show
      @accountdetails = Accountdetail.where("user_id = ?",@user.id)
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(admin_params)
      if @user.save
        @user.add_role :employee
        redirect_to admin_users_path
      else
        render :new
      end
    end

    def edit; end

    def update
      if @user.update(admin_params)
        redirect_to admin_users_path, notice: 'updated succesfully'
      else
        render :edit
      end
    end

    def destroy
      @user.destroy
      redirect_to admin_users_path
    end

    private

    def admin_params
      base_params = params.require(:user).permit(:name, :email, :phone, :gender, :state_id, :city_id, :company_id, :department_id, 
                                                  accountdetails_attributes: [:id, :user_id, :branch_name, :account_number, :account_name, :image, :_destroy])
      if action_name == 'update'
        base_params
      else
        password = params.dig('user', 'password')
        password_confirmation = params.dig('user', 'password_confirmation')
        base_params.merge(password: password, password_confirmation: password_confirmation)
      end
    end

    def restrict_user
      unless current_user.has_role? :admin
        if current_user.has_role? :superadmin
          redirect_to superadmin_users_path
        elsif current_user.has_role? :employee
          redirect_to employee_user_path(current_user)
        else
          redirect_to root_path
        end
      end
    end

    def set_admin_user
      @user = User.joins(:state, :city).select("users.*, states.name as state_name, cities.name as city_name").find(params[:id])
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < Api::V1::BaseController
      before_action :process_token
      skip_before_action :verify_authenticity_token
      before_action :set_user, only: %i[show update destroy]

      def index
        @users = User.includes(:state, :city).all
      end

      def show; end

      def create
        @user = User.new(user_params)
        if @user.save
          success_json(@user, 'Created Successfully!')
        else
          err_json(@user.errors, 'something went wrong!', 422)
        end
      end

      def update
        if @user.update(user_params)
          success_json(@user, 'Updated Successfully!')
        else
          err_json(@user.errors, 'something went wrong!', 422)
        end
      end

      def destroy
        if @user.destroy
          success_json(@user, 'Deleted Successfully!')
        else
          err_json(@user.errors, 'something went wrong!', 404)
        end
      end

      private

      def user_params
        base_params = params.require(:user).permit(:name, :email, :phone, :gender, :state_id, :city_id)
        if action_name == 'update'
          base_params
        else
          password = params.dig('user', 'password')
          base_params.merge(password: password)
        end
      end

      def set_user
        @user = User.find(params[:id])
      end
    end
  end
end

app/controllers/employee/users_controller.rb
# frozen_string_literal: true

# This conntroller used to display userdetails
module Employee
  # This controller is for EmployeeUser
  class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :restrict_user
    before_action :set_employee_user, only: %i[show]
    load_and_authorize_resource

    def show
       @accountdetails = Accountdetail.where("user_id = ?",@user.id)
    end

    private

    def restrict_user
      unless current_user.has_role? :employee
        if current_user.has_role? :superadmin
          redirect_to superadmin_users_path, notice: 'You are not allowed!'
        elsif current_user.has_role? :admin
          redirect_to admin_users_path, notice: 'You are not allowed!'
        else
          redirect_to root_path
        end
      end
    end

    def set_employee_user
      @user = User.left_joins(:state, :city).select("users.*, states.name as state_name, cities.name as city_name").find(params[:id])
    end
  end
end

app/controllers/superadmin/users_controller.rb
# frozen_string_literal: true

# This conntroller used to display userdetails
module Superadmin
  # This controller is for SuperadminUser
  class UsersController < ApplicationController
    load_and_authorize_resource param_method: :superadmin_params
    before_action :authenticate_user!
    before_action :restrict_user
    before_action :set_superadmin_user, only: %i[show edit update destroy]
    decorates_assigned :user

    def index
      if params[:search]
        @users = User.search(params[:search])
      else
        @users = User.add_extra.employee_and_admin_users.decorate.order(:id)
      end
      respond_to do |format|
        format.html
        format.js
        #format.csv { send_data @users.to_csv, filename: "users-#{Date.today}.csv" }
        format.csv do
          #headers['Content-Type'] ||= 'text/csv'
          send_data User.to_csv(@users), filename: "users-#{Date.today}.csv"
        end
      end
    end

    def import
      result = User.import(params[:file])
      if result.include? 'success'
        redirect_to superadmin_users_path, notice: "Successfully imported!"
      else
        redirect_to superadmin_users_path, alert: "#{result[0].join(",")} in #{result[-1].ordinalize} row of  CSV file"
      end
    end

    def show
      @accountdetails = Accountdetail.where("user_id = ?",@user.id) 
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(superadmin_params)
      if @user.save
        @user.add_role params.dig('user', 'role')
        redirect_to superadmin_users_path
      else
        render :new
      end
    end

    def edit; end

    def update
      @user.undiscard if params.dig(:restore)
      if @user.update(superadmin_params)
        redirect_to superadmin_users_path, notice: 'updated succesfully'
      else
        render :edit
      end
    end

    def destroy
      if @user.discarded?
        @user.destroy
      else
        @user.discard
      end
      redirect_to superadmin_users_path
    end

    private

    def superadmin_params
      base_params = params.require(:user).permit(:name, :email, :phone, :gender, :state_id, :city_id, :company_id, :department_id, 
                                                  accountdetails_attributes: [:id, :user_id, :branch_name, :account_number, :account_name, :image, :_destroy])
      if action_name == 'update'
        base_params
      else
        password = params.dig('user', 'password')
        password_confirmation = params.dig('user', 'password_confirmation')
        base_params.merge(password: password, password_confirmation: password_confirmation)
      end
    end

    def restrict_user
      unless current_user.has_role? :superadmin
        if current_user.has_role? :admin
          redirect_to admin_users_path
        elsif current_user.has_role? :employee
          redirect_to employee_user_path(current_user)
        else
          redirect_to root_path
        end
      end
    end

    def set_superadmin_user
      @user = User.left_joins(:state, :city).select("users.*, states.name as state_name, cities.name as city_name").find(params[:id])
    end
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

# This is userdetails helper.
module UserHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# This is userdetails helper.
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container mt-3">
<h2>Edit User</h2>
<%= form_with model: @user, url: admin_user_path(@user), method: 'patch' do |f| %>
  <div class="form-group row">
    <%= f.label :name,  class:"col-sm-2 col-form-label" %><br />
    <div class="col-sm-8">
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
    </div>
  </div>

   <div class="form-group row">
    <%= f.label :email, class:"col-sm-2 col-form-label" %><br />
    <div class="col-sm-8">
    <%= f.email_field :email, autofocus: true, autocomplete: "email",class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :phone, class:"col-sm-2 col-form-label" %><br />
    <div class="col-sm-8">
    <%= f.text_field :phone, autofocus: true,class: "form-control" %>
    </div>
  </div>

  <fieldset class="form-group">
  <div class="row">
    <%= f.label :Gender,class:"col-sm-2 col-form-label" %>
    <div class="col-sm-8">
    <%= f.radio_button(:gender, "male") %>
    <%= label(:gender, "Male") %>
    <%= f.radio_button(:gender, "female")%>
    <%= label(:gender, "Female") %>
    </div>
  </div>
  </fieldset>

  <div class="form-group row">
    <%= f.label :state_id, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-8">
    <%= f.collection_select(:state_id, State.includes(:cities).all, :id, :name, :prompt => 'Select a State') %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :city_id,class:"col-sm-2 col-form-label" %>
     <div class="col-sm-8">
    <%= f.grouped_collection_select(:city_id, State.all,:cities,:name,:id, :name, :prompt => 'Select a City') %>
     </div>
  </div>

  <div class="actions">
    <%= f.submit "Update", class:"btn btn-info btn-sm" %>
  </div>
<% end %>
<%= link_to 'Back', admin_users_path%>
</div> 

app/views/admin/users/index.html.erb
<div class="container">
<h1 class="text-center">Employee details</h1>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Gender</th>
      <th scope="col">Company</th>
      <th scope="col">State</th>
      <th scope="col">City</th>
      <th scope="col" colspan=4, class="text-center">Action</th>
    </tr>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.gender %></td>
        <td><%= user.company_name %></td>
        <td><%= user.state_name %></td>
        <td><%= user.city_name %></td>
        <td><%= link_to 'show',admin_user_path(user), class:'btn btn-outline-primary btn-sm' %></td>
        <td><%= link_to 'Edit',edit_admin_user_path(user), class:'btn btn-outline-secondary btn-sm' %></td>
        <% if can? :destroy, user%>
        <td><%= link_to 'Destroy',admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?'}, class:'btn btn-outline-danger btn-sm'  %></td>
        <% end %>
        <td><%= link_to 'Add details', new_accountdetail_path(user_id: user), class:'btn btn-outline-info btn-sm', style: 'font-size:smaller' %></td>      
        <td><%= link_to 'Show details', accountdetails_path(user_id:user), class:'btn btn-outline-dark btn-sm', style: 'font-size:smaller' %></td>  
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/admin/users/new.html.erb
<div class="container">
<h2>Create New</h2>
<%= form_with model: @user, url: admin_users_path do |f| %>
  <div class="form-group row">
    <%= f.label :name,  class:"col-sm-2 col-form-label" %><br />
    <div class="col-sm-8">
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :email, class:"col-sm-2 col-form-label" %><br />
    <div class="col-sm-8">
    <%= f.email_field :email, autofocus: true, autocomplete: "email",class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :phone, class:"col-sm-2 col-form-label" %><br />
    <div class="col-sm-8">
    <%= f.text_field :phone, autofocus: true,class: "form-control" %>
    </div>
  </div>

  <fieldset class="form-group">
  <div class="row">
    <%= f.label :Gender,class:"col-sm-2 col-form-label" %>
    <div class="col-sm-8">
    <%= f.radio_button(:gender, "male") %>
    <%= label(:gender, "Male") %>
    <%= f.radio_button(:gender, "female")%>
    <%= label(:gender, "Female") %>
    </div>
  </div>
  </fieldset>

  <div class="form-group row">
    <%= f.label :state_id, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-8">
    <%= f.collection_select(:state_id, State.all, :id, :name, :prompt => 'Select a State') %>
    </div>
  </div>
  
  <div class="form-group row">
    <%= f.label :city_id,class:"col-sm-2 col-form-label" %>
     <div class="col-sm-8">
      <%= f.select(:city_id, @cities = [] ,{prompt: "Select a City"}) %>
     </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-2 col-form-label">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <div>
    <em>(minimum <%= @minimum_password_length %> characters)</em>
    </div>
    <% end %>
    </div>
    <div class="col-sm-8">
    <%= f.password_field :password, autocomplete: "new-password", class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :password_confirmation,class:"col-sm-2 col-form-label" %><br />
    <div class="col-sm-8">
    <%= f.password_field :password_confirmation, autocomplete: "new-password", class:"form-control" %>
    </div>
  </div>
  
  <div class="actions">
    <%= f.submit "add new",class:"btn btn-primary btn-sm" %><br/>
  </div>
<% end %>
<%= link_to 'Back', admin_users_path%>
</div>

<script type="text/javascript">
  $(document).on("change", "#user_state_id", function(){
  var state = $(this).val();
  console.log(state)
  $.ajax({
    url: "/cities",
    method: "GET",  
    dataType: "json",
    data: {state_id: state},
    error: function (xhr, status, error) {
      console.error('AJAX Error: ' + status + error);
    },
    success: function (response) {
      console.log(response);
      var cities = response["cities"];
      $("#user_city_id").empty();

      $("#user_city_id").append('<option>Select city</option>');
      for(var i=0; i< cities.length; i++){
        $("#user_city_id").append('<option value="' + cities[i]["id"] + '">' + cities[i]["name"] + '</option>');
      }
    }
  });
});
</script>

app/views/admin/users/show.html.erb
<div class="container">
    <h1>show page</h1>
    <p><b>Name:</b><%= @user.name %></p>
    <p><b>Email:</b><%= @user.email%></p>
    <p><b>Phone:</b><%= @user.phone%></p>
    <p><b>Gender:</b><%= @user.gender%></p>
    <p><b>State:</b><%= @user.state_name%></p>
    <p><b>City:</b><%= @user.city_name%></p>
    <p><b>Accountdetails:</b>
        <div class="row m-2">
            <% @accountdetails.each do |account_detail| %>
                <div class="card mt-2 ml-2" style="width: 18rem;">
                    <div class="card-body">
                        <p class="card-text"><b>Acc_Name:</b><%= account_detail.account_name %></p>
                        <p class="card-text"><b>Acc_Number:</b><%= account_detail.account_number %></p>
                        <p class="card-text"><b>Branch_Name:</b><%= account_detail.branch_name %></p>
                    </div>
                </div>
            <% end %>
        </div>
    </p>
    <%= link_to 'Back', admin_users_path%>
</div> 