config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  devise_for :users,controllers: { omniauth_callbacks: 'omniauth' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/cities', to: 'home#getcities'
  resources :accountdetails, path: 'account_details' do
    collection do
      get 'accountdetails/:user_id', to: 'accountdetails#index', as: :details
    end
  end
  
  get '/companies', to: 'home#getdepartments'
  namespace :admin do
    resources :users
  end

  namespace :employee do
    resources :users, only: %i[show]
  end

  namespace :superadmin do
    resources :users do
      collection { post :import }
    end
    resources :companies do
      resources :departments
    end
  end

  namespace 'api' do
    namespace 'v1' do
      devise_for :users, defaults: { format: :json },
                         controllers: { sessions: 'api/v1/api_sessions', registrations: 'api/v1/api_registrations' }
      resources :users, except: %i[new edit]
    end
  end
  resources :memberships, only: %i[new]
  post :create_order, to: 'memberships#create_order'
  post :capture_order, to: 'memberships#capture_order'

  get '/users', to: 'posts#users'
  post 'users/:id/posts', to: 'posts#save_post'
  post 'users/:id/post', to: 'posts#create_post'
end

app/views/layouts/_form.html.erb
<%= form_with model: @accountdetail, url: url do |f| %>

  <%#= f.hidden_field :user_id, value: params[:user_id] %>
  <%= f.hidden_field :user_id, value: @accountdetail.user_id %>

  <div class="form-group row">
    <%= f.label :branch_name,  class:"col-sm-2 col-form-label" %><br />
    <div class="col-sm-8">
    <%= f.text_field :branch_name, autofocus: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :account_number, class:"col-sm-2 col-form-label" %><br />
    <div class="col-sm-8">
    <%= f.number_field :account_number, autofocus: true,class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :account_name, class:"col-sm-2 col-form-label" %><br />
    <div class="col-sm-8">
    <%= f.text_field :account_name, autofocus: true,class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :image, class:"col-sm-2 col-form-label" %><br />
    <div class="col-sm-8">
    <%= f.file_field :image %>
    </div>
  </div>
  
  <div class="actions">
    <%= f.submit @accountdetail.new_record? ? "Add" : "Update" ,class:"btn btn-primary btn-sm" %><br/>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Demo', root_path, class:'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if current_user.has_role? :superadmin %>
          <li class="nav-item active">
              <%= link_to 'Users list',superadmin_users_path, class: 'nav-link' %>
          </li>
        <% elsif current_user.has_role? :admin %>
          <li class="nav-item active">
              <%= link_to 'Users list',admin_users_path, class: 'nav-link' %>
          </li>
        <% else %>
            <li class="nav-item active">
              <%= link_to 'Users list',employee_user_path(current_user), class: 'nav-link' %>
            </li>
      <% end %>
      <li class="nav-item active">
          <%= link_to 'Buy Membership',new_membership_path , class:'nav-link' %>
      </li>   
      <li class="nav-item active">
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class:'nav-link' %>
      </li>  
    </ul>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        My Profile
      </button>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <% if not current_user.has_role? :employee %>
          <%= link_to 'New User', new_superadmin_user_path, class: 'dropdown-item' %>
        <% end %>
        <% if current_user.has_role? :superadmin%>
            <%= link_to 'Add Company',new_superadmin_company_path, class: 'dropdown-item' %> 
            <%= link_to 'Show Companies',superadmin_companies_path, class: 'dropdown-item' %>
        <% end %>
        <%= link_to 'Edit Profile', edit_user_registration_path,class:'dropdown-item' %>
        <%= link_to 'Add my details', new_accountdetail_path(user_id:current_user.id), class: 'dropdown-item' %>
        <%= link_to 'View my details', accountdetails_path(user_id:current_user.id),  class: 'dropdown-item' %>
      </div>
    </div>
    <% end %>
  </div>
</nav>
  <% if flash[:notice] %>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice]%>
    </div>
  <% elsif flash[:error]%>
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error]%>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert]%>
    </div>
  <% end %>
    <%= yield %>
  </body>
</html>